In [5]:
import numpy as np

In [7]:
a = np.arange(5)

In [13]:
a.shape

(2, 2)

In [10]:
a.shape

(5,)

In [11]:
a = np.array([[1,2],[3,4]])

In [15]:
b = a+1

In [16]:
b

array([[2, 3],
       [4, 5]])

In [20]:
l = [[2,3],[4,5]]

In [21]:
l[0][1]

3

In [22]:
b[0,1]

3

In [23]:
b

array([[2, 3],
       [4, 5]])

In [24]:
b.transpose()

array([[2, 4],
       [3, 5]])

In [26]:
b = np.arange(16).reshape((4,4))

In [27]:
b

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [28]:
b.transpose()

array([[ 0,  4,  8, 12],
       [ 1,  5,  9, 13],
       [ 2,  6, 10, 14],
       [ 3,  7, 11, 15]])

In [34]:
a = np.random.random((3,4,5,6))

In [35]:
a

array([[[[3.68967933e-01, 9.69104255e-01, 2.44425462e-01,
          6.63399164e-01, 3.07734691e-01, 3.87306718e-01],
         [5.37459895e-01, 8.65327837e-01, 6.63410304e-01,
          6.13593939e-01, 1.79450464e-01, 5.29383606e-01],
         [7.31613933e-01, 1.22497771e-01, 8.01088636e-01,
          8.50609166e-01, 3.65906758e-01, 6.71840443e-01],
         [7.03578123e-01, 1.80037945e-01, 7.00523924e-01,
          2.31580454e-01, 3.11920824e-01, 4.54010704e-01],
         [8.61913899e-01, 9.93910169e-01, 4.41553155e-01,
          5.62721821e-01, 6.65748040e-01, 9.52805145e-02]],

        [[8.95733043e-01, 2.72340078e-01, 7.27167302e-01,
          7.43677893e-02, 1.50530871e-01, 1.16858064e-01],
         [7.82005618e-01, 6.54055934e-02, 9.80855668e-01,
          3.84012682e-01, 1.73636346e-01, 9.64915133e-01],
         [1.50928246e-01, 3.61042375e-01, 4.66389525e-01,
          9.20810788e-01, 6.90872762e-02, 2.59244231e-01],
         [6.79049158e-01, 6.55183721e-01, 9.80513112e-01,
    

In [38]:
a = np.ones((3,3))

In [39]:
a

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [40]:
a = np.zeros((3,4))

In [41]:
a

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [44]:
b = np.eye(3,3)

In [45]:
b

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [46]:
np.save("b_xxx.py", b)

In [47]:
c = np.load("b_xxx.py.npy")

In [48]:
c

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [49]:
a

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [55]:
np.savetxt("a_xxxx", a, delimiter=".")

In [56]:
d = np.genfromtxt("a_xxxx", delimiter=".")

In [57]:
d

array([[0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.]])

In [58]:
a = np.random.random((3,4))

In [59]:
a

array([[0.13662957, 0.92342748, 0.10814142, 0.97883414],
       [0.94736775, 0.36725167, 0.30825549, 0.43755935],
       [0.49425296, 0.70912102, 0.01368915, 0.36007129]])

In [60]:
a.sum()

5.7846012948593435

In [61]:
a.shape

(3, 4)

In [62]:
a.sum(axis = 0)

array([1.57825028, 1.99980017, 0.43008607, 1.77646478])

In [63]:
a.sum(axis = 1)

array([2.14703262, 2.06043426, 1.57713442])

In [64]:
a.shape

(3, 4)

In [65]:
b = np.random.random((4,5))

In [66]:
a.dot(b)

array([[0.99331745, 1.43148089, 1.26250669, 0.71519636, 1.0359997 ],
       [0.78348165, 1.11462878, 0.78063333, 0.98241979, 1.20505246],
       [0.48789791, 1.0075165 , 0.66807288, 0.52571756, 0.87645585]])

In [67]:
np.dot(a,b)

array([[0.99331745, 1.43148089, 1.26250669, 0.71519636, 1.0359997 ],
       [0.78348165, 1.11462878, 0.78063333, 0.98241979, 1.20505246],
       [0.48789791, 1.0075165 , 0.66807288, 0.52571756, 0.87645585]])